### ISSUE TITLE
Test report template

### ISSUE THREAD

**Issue by Lechros** [simaple-team/simaple#138]
직업별로 test report 코드 구현 방식이 달라 양식을 통일해야 합니다.

**Comment by oleneyl** [comment]
Report 쪽 테스트를 tests/data 계층으로 옮겨야 할 것 같습니다. 실제 데이터에 관련된 부분인만큼 하위 레벨인 simulate에 속하지 않아야 할 것 같은데, 어떻게 생각하시나요?

**Comment by Lechros** [comment]
simulate 외부로 옮기는 것에 동의합니다.
추가로 계산 과정에서 직업 별로 스탯을 직접 입력하지 않고 client_configuration과 baseline을 사용하면 좋겠습니다.
