### ISSUE TITLE
fetch의 반환값에 누락되는 정보가 있음

### ISSUE THREAD

**Issue by Lechros** [simaple-team/simaple#179]
홈페이지에서 제공되는 `물리방어력` 항목이 fetch에서도 모두 반환되어야 합니다.

![image](https://github.com/simaple-team/simaple/assets/6011621/c64eae7e-8d8e-4c37-a22e-814ce1b19ed1)

장비 속성 중에 `교환 불가`, `1회 교환가능 (거래 후 교환불가)`, `황금망치 적용 불가` 등이 포함되어야 합니다. (글자 색 `Orange`로 구분 가능)

**Comment by oleneyl** [comment]
공식 API 지원으로 close.
