### ISSUE TITLE
Potential data validity checks

### ISSUE THREAD

**Issue by Lechros** [simaple-team/simaple#58]
스킬 yaml을 구현하는 과정에서 실수할만한 부분에 대한 검사를 추가하고자 합니다.

- 파일명과 label의 group이 다른 경우 (ex. archmagefb.yaml에서 group: archmagetc)
- 동일한 group에 중복된 스킬명이 있는 경우 (ex. 패시브와 액티브에 중복 구현)
- yaml의 listening_actions가 실제로 존재하는지 (ex. component 구현이 바뀔 경우)

**Comment by oleneyl** [comment]
좋습니다. 어떤 식으로 구현하실 예정인가요?

**Comment by OniOniOn-** [comment]
1, 2번은 loader 구현을 참고하고, 3번은 load all하고 함수명이 컴포넌트에 있는지 확인할 계획입니다. 구현 전에 archmagefb, adventurer, magician 관계를 저장해야 할 것 같습니다.

**Comment by oleneyl** [comment]
테스트 라이브러리는 뭘 쓰고, 테스트 코드는 어디에 위치하게 되나요?

**Comment by OniOniOn-** [comment]
기존에 사용하던 pytest를 사용하고, data/test_skill_resources.py에 작성됩니다.

**Comment by oleneyl** [comment]
테스트가 별개의 디렉토리에 있는건 어떤가요? /validation/ 이라던가?

**Comment by OniOniOn-** [comment]
별개의 디렉토리에 (각각의 파일로) 구현해도 좋을 것 같습니다.

**Comment by oleneyl** [comment]
음..이 이상은 구현체를 봐야 알것같네요
